### ISSUE TITLE
Nodes visibility on Dynmap

### ISSUE THREAD

**Issue by 3meraldK** [phonon/minecraft-nodes#2]
Read readmes and the docs, to no avail. Dynmap doesn't show you territories. /nodes lists them correctly. They aren't shown on Dynmap. Every step followed carefully. Tried on 1.16.5 and 1.18 (dev branch). Please fix your plugin.

**Comment by 3meraldK** [comment]
Solved

**Comment by yonxel** [comment]
can you help me? i have the same error, my discord is: .yonxel

**Comment by mamatheus0077** [comment]
Hello, I have the same error too. Could you help me?? 
My discord is mamatheus07
